name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 16.171.173.60  # EC2 instance IP adresiniz
        username: ubuntu  # EC2 instance'ınızın kullanıcı adı (Amazon Linux için 'ec2-user', Ubuntu için 'ubuntu')
        key: ${{ secrets.EC2_KEY }}  # Private key'inizi GitHub Secrets'a ekleyin ve burada çağırın
        port: 22
        script: |
          cd /home/ubuntu/phpblogcicd
          git stash || true
          git pull
          sudo mv /phpblogcicd /var/www/html
