name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 13.61.2.143  # EC2 instance IP adresiniz
        username: ubuntu  # EC2 instance'ınızın kullanıcı adı (Amazon Linux için 'ec2-user', Ubuntu için 'ubuntu')
        key: ${{ secrets.EC2_KEY }}  # Private key'inizi GitHub Secrets'a ekleyin ve burada çağırın
        port: 22
        script: |
          cd /home/ubuntu/cicdtry  # Uygulamanın bulunduğu dizine gidin (örneğin /home/ubuntu/myapp)
          git stash || true
          git pull
          npm install --unsafe-perm=true
          sudo pm2 restart my-app -f || pm2 start /home/ubuntu/cicdtry/index.js --name my-app -f